#
#logging:
#  config: src/main/resources/logback-spring.xml
#server:
#  port: 9999

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: Test
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver